---
- name: Download gitlab_cli_package_url
  ansible.builtin.get_url:
    url: "{{ gitlab_cli_package_url }}"
    dest: "{{ gitlab_cli_package_path }}/{{ gitlab_cli_package_url | basename }}"
    mode: "0644"

- name: Install gitlab_cli
  ansible.builtin.yum:
    name: "{{ gitlab_cli_package_path }}/{{ gitlab_cli_package_url | basename }}"
    state: present
    disable_gpg_check: true

...
